language: node_js
node_js:
  - '0.12'
  - '4.0'
  - 'iojs'
services: mongodb
before_install:
  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - which brew
  - brew update
  - brew outdated mongodb || brew upgrade mongodb
